cache:
  directories:
  - "$HOME/.m2"
language: java
jdk:
- oraclejdk8
notifications:
  slack:
    secure: 2/3NDxSqDpGA7PL5NMKNgcpX3uGmzi2FJ5b+aw2Xwm5DGDAANRFuHsK1amvg+FfY6K0E2IzpDwgvRDTW3wn1mpe9HJNuPePnJSRPOp84cPRs5htgz36Hr8Se+Sxt8bz9FEun+xnJ1OG2LObSMzIz0fllsMgfWLt3FeY7zCj34LloKNsWKrYAkwxG90t4m21Jqxk4sP2EkHCz/FGOdBafTZ5/Aa6BUsIJtC94AGKKjB/ZbUxqb9vZr9Ay5yrf/1S6TovCaIOGB5WyaDhsr47myHRr920cV1i3u/TywPZxlVrJph09NUP+0+HyhDtcVUu5dWp22uo4Q91SuS7ONG8fFvr/vmHji1IK3cR3t4Nifb/UDi3bq4tDaNdYBGG/mnvVHNSQ8M2UQ9aMub5SuwWz+BnkIy0m3qCHJWp5ESDCN34vcN7t2ZJHk5wybRUw6WI7BkFSQTbeoPSLhLyu4NjAYriMYinwSs+fG1SZxM6uLPjvl6sjBzl23xQTZPYNi1wXLZHvpm7HmrrJdZ7YC5xpCX/WUAPpy6Rq5pM4f4aVSl8ysKROgWivuSFqzGE0W7KccfwnRWrXhivaxTU/LDkyRod/SLaiW/A1BBypmjxXaj3o65BAJOEdwGkxAuKPcCGto6yPnkCoQCcn0Yws66z0tFzLDB6g6Spiw75t+g6MxGs=
